### ISSUE TITLE
jeecg-boat v3.7.0_all   登录后就无限loading

### ISSUE THREAD

**Issue by LHK8088** [jeecgboot/JeecgBoot#6868]
##### 版本号：jeecg-boat v3.7.0_all
https://github.com/jeecgboot/JeecgBoot  master 分支

##### 问题描述：登录后就无限loading
携带cookie 直接访问localhost:3100 就会无限loading,报错
![image](https://github.com/jeecgboot/JeecgBoot/assets/131111425/4ff56c2f-ebcf-4177-8bcc-de9161edb5dd)

在无痕浏览器模式下,可以成功访问到 登录页面,但是点击登录后就会进入 无限loading,尝试无期限等待,一直到页面崩溃.

我曾经在2024-7-8 成功进入过功能页面 并且使用了一些示例,但是在2024-7-9 下午就 出现了无法使用的问题(登录后无限loading)

第一次出现这个问题时候还是局域网内 访问ip出现的故障,但是本地 localhost:3100 是没问题的,但是现在 localhost也无法正常运行了,

希望能告知为何出现此问题,谢谢
##### 错误截图：

![037dd0c79cd00207bf6d1a63adead3dd](https://github.com/jeecgboot/JeecgBoot/assets/131111425/016a3732-caed-4d69-80d2-100cf78142e9)
![614b0e0c2a69b91d53e3ba71401322c6](https://github.com/jeecgboot/JeecgBoot/assets/131111425/8b880f5e-eefd-4cf5-b151-0c69982ae3fc)
![97b5dde654f981d698786d98ded88871](https://github.com/jeecgboot/JeecgBoot/assets/131111425/ed8797e0-d660-4597-887e-26b420be2545)

报错截图:
携带cookie 和首次登录的报错
![image](https://github.com/jeecgboot/JeecgBoot/assets/131111425/3d272cec-5e6b-4d79-8723-b4bece78275a)
第一次报错后,在无痕登录 就不会出现这个问题,只会记录日志 全是登录接口的日志,但是实际结果 还是在无限loading
![image](https://github.com/jeecgboot/JeecgBoot/assets/131111425/2cb28cec-2309-4b5e-9e18-3925a3641fb6)

**Comment by LHK8088** [comment]
尝试过的方法:
重新克隆全量代码,重新安装 Maven,重新安装, 前端项目,重新 pnmp install,均无效

**Comment by zhangdaiscott** [comment]
百度搜下后台的错误

**Comment by zhangdaiscott** [comment]
后台问题跟前端无关

**Comment by LHK8088** [comment]
控制台日志,代码没有改动过, 这个错误信息与 Apache Shiro 的 RememberMe 功能有关，具体是由于在解密记住的身份时发生了问题

![image](https://github.com/jeecgboot/JeecgBoot/assets/131111425/7c0df1d6-75b8-43a7-9375-b658d48029b6)
![image](https://github.com/jeecgboot/JeecgBoot/assets/131111425/0e91274e-5653-48a8-b1bb-977519b5a431)

**Comment by LHK8088** [comment]
堆栈:
2024-07-09 16:48:44.191 [http-nio-8080-exec-2] WARN  org.apache.shiro.mgt.AbstractRememberMeManager:449 - There was a failure while trying to retrieve remembered principals.  This could be due to a configuration problem or corrupted principals.  This could also be due to a recently changed encryption key, if you are using a shiro.ini file, this property would be 'securityManager.rememberMeManager.cipherKey' see: http://shiro.apache.org/web.html#Web-RememberMeServices. The remembered identity will be forgotten and not used for this request.
2024-07-09 16:48:44.191 [http-nio-8080-exec-2] WARN  org.apache.shiro.mgt.DefaultSecurityManager:618 - Delegate RememberMeManager instance of type [org.apache.shiro.web.mgt.CookieRememberMeManager] threw an exception during getRememberedPrincipals().
org.apache.shiro.crypto.CryptoException: Unable to correctly extract the Initialization Vector or ciphertext.
	at org.apache.shiro.crypto.JcaCipherService.decrypt(JcaCipherService.java:378)
	at org.apache.shiro.mgt.AbstractRememberMeManager.decrypt(AbstractRememberMeManager.java:482)
	at org.apache.shiro.mgt.AbstractRememberMeManager.convertBytesToPrincipals(AbstractRememberMeManager.java:419)
	at org.apache.shiro.mgt.AbstractRememberMeManager.getRememberedPrincipals(AbstractRememberMeManager.java:386)
	at org.apache.shiro.mgt.DefaultSecurityManager.getRememberedIdentity(DefaultSecurityManager.java:613)
	at org.apache.shiro.mgt.DefaultSecurityManager.resolvePrincipals(DefaultSecurityManager.java:501)
	at org.apache.shiro.mgt.DefaultSecurityManager.createSubject(DefaultSecurityManager.java:347)
	at org.apache.shiro.subject.Subject$Builder.buildSubject(Subject.java:845)
	at org.apache.shiro.web.subject.WebSubject$Builder.buildWebSubject(WebSubject.java:148)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.createSubject(AbstractShiroFilter.java:300)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:367)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:61)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:458)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:373)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:387)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:370)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:154)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:178)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:153)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:168)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:481)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:130)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:390)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:928)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1794)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.base/java.lang.Thread.run(Thread.java:1570)
Caused by: java.lang.ArrayIndexOutOfBoundsException: arraycopy: last source index 16 out of bounds for byte[3]
	at java.base/java.lang.System.arraycopy(Native Method)
	at org.apache.shiro.crypto.JcaCipherService.decrypt(JcaCipherService.java:370)
	... 69 common frames omitted

**Comment by LHK8088** [comment]
清楚 cookie 不会报错但是没有实际效果,依然无限loading,我看不仅我碰到过此问题,五个小时前也有相同的问题反馈

![image](https://github.com/jeecgboot/JeecgBoot/assets/131111425/43f28ac9-981b-478b-a728-51a89508c52c)

**Comment by zhangdaiscott** [comment]
https://www.cnblogs.com/kkxwze/p/13355632.html

**Comment by zhangdaiscott** [comment]
我们没遇到过

**Comment by zhangdaiscott** [comment]
最简单的方式，直接删除浏览器cookie。
https://blog.csdn.net/u010786653/article/details/126028780
