### ISSUE TITLE
jeecgBoot 3.7.1 版本 dubbo集成  添加DubboReference注解后启动报错

### ISSUE THREAD

**Issue by MrJson1** [jeecgboot/JeecgBoot#7282]
##### 问题描述：
jeecgBoot 3.7.1 版本 添加DubboReference注解后启动报错

##### 错误截图：

报错信息如下：

```
Exception in thread "Quartz Scheduler [MyScheduler]" org.springframework.scheduling.SchedulingException: Could not start Quartz Scheduler after delay; nested exception is org.quartz.SchedulerException: The Scheduler cannot be restarted after shutdown() has been called.
	at org.springframework.scheduling.quartz.SchedulerFactoryBean$1.run(SchedulerFactoryBean.java:756)
Caused by: org.quartz.SchedulerException: The Scheduler cannot be restarted after shutdown() has been called.
	at org.quartz.core.QuartzScheduler.start(QuartzScheduler.java:529)
	at org.quartz.impl.StdScheduler.start(StdScheduler.java:142)
	at org.springframework.scheduling.quartz.SchedulerFactoryBean$1.run(SchedulerFactoryBean.java:753)
```

去除注解后正常启动

```
//    @DubboReference(check = false)
//    private DevopsDubboService devopsDubboService;
```

**Comment by zhangdaiscott** [comment]
这种自己扩展问题，需要自己解决

**Comment by MrJson1** [comment]
什么东西都还没有干呢，第一步就不得行，你们都把代码的结构写死了，使用以前的3.0版本都没有这个问题，怎么感觉你们越优化越差，不应该考虑扩展性问题？都不可以扩展其他的

**Comment by MrJson1** [comment]
扩展的成本，还首先来解决你们这边的问题，那就无法玩了
